apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api-v2
  template:
    metadata:
      labels:
        app: inventory-api-v2
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: inventory-api-v2
          image: ghcr.io/marcel-platform/inventory-api-v2:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080