apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: invoice-service
          image: ghcr.io/marcelphilippeandrade/invoice-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 5
