apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: springboot-service
  title: Create Spring Boot Service
  description: Generate a new Spring Boot microservice

spec:
  owner: user:guest
  type: service

  parameters:
    - title: Service Information
      required:
        - serviceName
        - packageName
        - containerPort
        - nodePort

      properties:
        serviceName:
          title: Service Name
          type: string
          description: Name of the microservice

        packageName:
          title: Package Name
          type: string
          description: Java package

        containerPort:
          title: Container Port
          type: number
          description: Port the application will listen on

        nodePort:
          title: Node Port
          type: number
          description: Port to expose the service on the cluster

  steps:

    - id: generate-service
      name: Generate Spring Boot Service
      action: platform:create-service
      input:
        serviceName: ${{ parameters.serviceName }}
        packageName: ${{ parameters.packageName }}
        containerPort: ${{ parameters.containerPort }}
        nodePort: ${{ parameters.nodePort }}

  output:
    text:
      - title: Service Created
        content: |
          Service Name:
          ${{ steps['generate-service'].output.serviceName }}

          Package:
          ${{ steps['generate-service'].output.packageName }}

          Container Port:
          ${{ steps['generate-service'].output.containerPort }}

          Node Port:
          ${{ steps['generate-service'].output.nodePort }}

          Location:
          ${{ steps['generate-service'].output.location }}
