apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: springboot-service
  title: Create Spring Boot Service
  description: Generate a new Spring Boot microservice

spec:
  owner: user:guest
  type: service

  parameters:
    - title: Service Information
      required:
        - serviceName
        - packageName
        - containerPort
        - nodePort
        - repositoryName
        - owner

      properties:
        serviceName:
          title: Service Name
          type: string
          description: Name of the microservice

        packageName:
          title: Package Name
          type: string
          description: Java package

        containerPort:
          title: Container Port
          type: number
          description: Port the application will listen on

        nodePort:
          title: Node Port
          type: number
          description: Port to expose the service on the cluster

        repositoryName:
          title: Repository Name
          type: string
          description: GitHub repository name

        owner:
          title: Owner
          type: string
          description: Team responsible for the service

  steps:
    - id: generate-service
      name: Generate Spring Boot Service
      action: platform:create-service
      input:
        serviceName: ${{ parameters.serviceName }}
        packageName: ${{ parameters.packageName }}
        containerPort: ${{ parameters.containerPort }}
        nodePort: ${{ parameters.nodePort }}
        owner: ${{ parameters.owner }}

    - id: create-github-repository
      name: Create GitHub Repository
      action: github:repo:create
      input:
        repoUrl: github.com?owner=marcel-platform&repo=${{ parameters.repositoryName }}
        description: Spring Boot service generated by Backstage
        defaultBranch: main

    - id: push-to-github
      name: Push Source Code
      action: github:repo:push
      input:
        repoUrl: github.com?owner=marcel-platform&repo=${{ parameters.repositoryName }}
        defaultBranch: main
        gitCommitMessage: Initial commit generated by Backstage
        gitAuthorName: Marcel Platform

    - id: register-catalog
      name: Register Component in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['push-to-github'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    text:
      - title: Service Created
        content: |
          Service Name:
          ${{ steps['generate-service'].output.serviceName }}

          Package:
          ${{ steps['generate-service'].output.packageName }}

          Container Port:
          ${{ steps['generate-service'].output.containerPort }}

          Node Port:
          ${{ steps['generate-service'].output.nodePort }}

          Repository:
          https://github.com/marcel-platform/${{ parameters.repositoryName }}
