apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-test-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-test-service
  template:
    metadata:
      labels:
        app: catalog-test-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: catalog-test-service
          image: ghcr.io/marcelphilippeandrade/catalog-test-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
