name: CI Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ '${{ github.actor }}' }}
          password: ${{ '${{ secrets.GITHUB_TOKEN }}' }}

      # Nome da imagem
      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/$(echo '${{ '${{ github.repository }}' }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Tag = commit SHA
      - name: Set image tag
        run: echo "IMAGE_TAG=${{ '${{ github.sha }}' }}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      # Deploy inteligente
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/payment-service payment-service=$IMAGE_NAME:$IMAGE_TAG

      - name: Wait for rollout
        run: kubectl rollout status deployment/payment-service

      - name: Rollback if failed
        if: failure()
        run: kubectl rollout undo deployment/payment-service
